export const prompts={
 discover:`You are a brand strategist. Analyze only the supplied rough idea and optional fields. Be concrete and empathetic. Return JSON exactly shaped {"discover":{"coreProblem":"","targetAudience":"","userContext":"","goals":[""],"constraints":[""],"assumptions":[""],"openQuestions":[""]}}. Distinguish known facts from assumptions.`,
 position:`Build strategic positioning from the original idea and discovery, not generic startup language. Return JSON {"positioning":{"category":"","targetAudience":"","differentiator":"","valueProposition":"","competitiveAngle":"","oneLinePitch":""}}.`,
 directions:`Create exactly three genuinely distinct strategic brand directions grounded in the idea, discovery and positioning. Each has {"id":"01","name":"","archetype":"","idea":"","personality":[""],"positioning":"","visualMood":"","tone":"","tagline":"","rationale":"","avoid":[""]}. Return {"directions":[...]}. Do not make superficial variations.`,
 shape:`Use original idea, discovery, positioning AND selectedDirection as binding context. Return {"shape":{"personality":{"traits":[""],"avoid":[""]},"naming":{"territories":[""],"names":[{"name":"","rationale":""}],"selectedName":""},"tagline":"","messageHierarchy":[""],"voice":""}}. Names should be distinctive, explainable and varied.`,
 visualize:`Translate selectedDirection and shaped identity into a coherent practical visual system. Return {"visualize":{"palette":[{"name":"","hex":"#000000"}],"typography":{"heading":"","body":"","display":""},"mood":"","imagery":"","shapes":"","composition":"","symbol":"","avoid":[""]}}. Include four usable contrasting palette colors.`,
 challenge:`Review the whole supplied brand system as a candid strategist. Score is a directional AI signal, not scientific measurement. Return {"challenge":{"works":[""],"generic":[""],"conflicts":[""],"changes":[""],"score":0}}. Keep findings specific and distinguish risks from facts.`,
 launch:`Write launch content using the complete supplied brand system and selected name/tagline. Return {"launch":{"headline":"","pitch":"","social":""}}. Avoid generic superlatives.`,
 consistency:`Evaluate supplied content against the established brand, audience, positioning, voice, personality and visual/messaging rules in brand context. This is a directional editorial signal. Return {"consistency":{"score":0,"matches":[""],"conflicts":[""],"revision":""}}. If content is empty, explain briefly and provide no invented evaluation.`
};
